# TinyUSB sources + release date header + dated firmware.bin copy.
Import("env")
from datetime import datetime
from pathlib import Path
import shutil

root = Path(env["PROJECT_DIR"])
tusb = root / "third_party_tinyusb" / "src"
inc = root / "include"
inc.mkdir(exist_ok=True)

now = datetime.now()
date_s = now.strftime("%Y-%m-%d")
datetime_s = now.strftime("%Y-%m-%d %H:%M:%S")
fw_base = "proficio-stm32f411-8MHz"
dated_name = f"{fw_base}-{date_s}.bin"

(build_hdr := inc / "build_info.h").write_text(
    "/* Auto-generated by extra_tinyusb.py — do not edit. */\n"
    "#ifndef PROFICIO_BUILD_INFO_H\n"
    "#define PROFICIO_BUILD_INFO_H\n"
    f'#define PROFICIO_FW_RELEASE_DATE     "{date_s}"\n'
    f'#define PROFICIO_FW_RELEASE_DATETIME "{datetime_s}"\n'
    f'#define PROFICIO_FW_BIN_NAME         "{dated_name}"\n'
    "#endif\n",
    encoding="utf-8",
)
print(f"build_info.h: release {datetime_s}")

env.Append(CPPPATH=[str(tusb)])

env.BuildSources(
    str(Path(env["BUILD_DIR"]) / "tinyusb"),
    str(tusb),
    src_filter=[
        "+<tusb.c>",
        "+<common/tusb_fifo.c>",
        "+<device/usbd.c>",
        "+<device/usbd_control.c>",
        "+<class/vendor/vendor_device.c>",
        "+<class/audio/audio_device.c>",
        "+<portable/synopsys/dwc2/dcd_dwc2.c>",
    ],
)


def _copy_dated_firmware(source, target, env):
    """After firmware.bin is built, also write proficio-…-YYYY-MM-DD.bin."""
    src_bin = Path(env.subst("$BUILD_DIR")) / f"{env.subst('$PROGNAME')}.bin"
    if not src_bin.is_file():
        print(f"dated firmware: missing {src_bin}")
        return
    build_copy = src_bin.with_name(dated_name)
    shutil.copy2(src_bin, build_copy)
    rel = root / "release"
    rel.mkdir(exist_ok=True)
    rel_copy = rel / dated_name
    shutil.copy2(src_bin, rel_copy)
    print(f"dated firmware: {build_copy}")
    print(f"dated firmware: {rel_copy}")


env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", _copy_dated_firmware)
