# TinyUSB sources + release date header + dated firmware.bin copy.
Import("env")
from datetime import datetime
from pathlib import Path
import shutil

root = Path(env["PROJECT_DIR"])
tusb = root / "third_party_tinyusb" / "src"
inc = root / "include"
inc.mkdir(exist_ok=True)

now = datetime.now()
date_s = now.strftime("%Y-%m-%d")
datetime_s = now.strftime("%Y-%m-%d %H:%M:%S")
fw_base = "proficio-stm32f411-25MHz"
dated_name = f"{fw_base}-{date_s}.bin"
# Virgin / factory image: bootloader (32KB) + app @ 0x08008000 (like PSoC combined .hex)
full_name = f"{fw_base}-{date_s}-full.bin"
BOOTLOADER_SIZE = 0x8000  # 32 KB

(build_hdr := inc / "build_info.h").write_text(
    "/* Auto-generated by extra_tinyusb.py — do not edit. */\n"
    "#ifndef PROFICIO_BUILD_INFO_H\n"
    "#define PROFICIO_BUILD_INFO_H\n"
    f'#define PROFICIO_FW_RELEASE_DATE     "{date_s}"\n'
    f'#define PROFICIO_FW_RELEASE_DATETIME "{datetime_s}"\n'
    f'#define PROFICIO_FW_BIN_NAME         "{dated_name}"\n'
    f'#define PROFICIO_FW_FULL_BIN_NAME    "{full_name}"\n'
    "#endif\n",
    encoding="utf-8",
)
print(f"build_info.h: release {datetime_s}")

env.Append(CPPPATH=[str(tusb)])

env.BuildSources(
    str(Path(env["BUILD_DIR"]) / "tinyusb"),
    str(tusb),
    src_filter=[
        "+<tusb.c>",
        "+<common/tusb_fifo.c>",
        "+<device/usbd.c>",
        "+<device/usbd_control.c>",
        "+<class/vendor/vendor_device.c>",
        "+<class/audio/audio_device.c>",
        "+<portable/synopsys/dwc2/dcd_dwc2.c>",
    ],
)


def _copy_dated_firmware(source, target, env):
    """After firmware.bin: app-only dated .bin + combined bootloader+app (full)."""
    src_bin = Path(env.subst("$BUILD_DIR")) / f"{env.subst('$PROGNAME')}.bin"
    if not src_bin.is_file():
        print(f"dated firmware: missing {src_bin}")
        return

    rel = root / "release"
    rel.mkdir(exist_ok=True)

    # 1) App-only (field update / cyacd equivalent) — flash at 0x08008000
    build_copy = src_bin.with_name(dated_name)
    shutil.copy2(src_bin, build_copy)
    rel_app = rel / dated_name
    shutil.copy2(src_bin, rel_app)
    print(f"dated firmware (app @ 0x08008000): {rel_app}")

    # 2) Combined virgin image — flash at 0x08000000 (bootloader + app)
    bl_path = rel / "bootloader.bin"
    if not bl_path.is_file():
        print(f"full firmware: SKIP (missing {bl_path})")
        return

    bl = bl_path.read_bytes()
    if len(bl) > BOOTLOADER_SIZE:
        print(
            f"full firmware: SKIP (bootloader {len(bl)} bytes > {BOOTLOADER_SIZE})"
        )
        return

    app = src_bin.read_bytes()
    combined = bl + (b"\xFF" * (BOOTLOADER_SIZE - len(bl))) + app

    full_build = src_bin.with_name(full_name)
    full_rel = rel / full_name
    full_build.write_bytes(combined)
    full_rel.write_bytes(combined)
    print(f"dated firmware (full @ 0x08000000): {full_rel}  ({len(combined)} bytes)")


env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", _copy_dated_firmware)
