# MSCC amplifier calibration status (client-only; managed by MSCC, not ms-sdr)
# AMP_B* = 0 not calibrated, 1 calibrated
AMP_B2200=0;
AMP_B630=0;
AMP_B160=1;
AMP_B80=1;
AMP_B60=1;
AMP_B40=1;
AMP_B30=1;
AMP_B20=1;
AMP_B17=1;
AMP_B15=1;
AMP_B12=1;
AMP_B10=1;
