/* Auto-generated by extra_tinyusb.py — do not edit. */
#ifndef PROFICIO_BUILD_INFO_H
#define PROFICIO_BUILD_INFO_H
#define PROFICIO_FW_RELEASE_DATE     "2026-09-12"
#define PROFICIO_FW_RELEASE_DATETIME "2026-09-12 19:56:52"
#define PROFICIO_FW_BIN_NAME         "proficio-stm32f411-25MHz-2026-09-12.bin"
#define PROFICIO_FW_FULL_BIN_NAME    "proficio-stm32f411-25MHz-2026-09-12-full.bin"
#endif
