#define CRC_MODE 0
#define CURSOR_HOME 1
#define SET_CURSOR 2
#define RESET_QUEUE 3
#define CLEAR_SCREEN 4
#define RESET_DISPLAY 5
#define SET_CURSOR_ROW_COLUMN 6
#define DATA 7

#define OPERATION_COMPLETED 3
#define OPERATION_PENDING 2 
#define OPERATION_STARTED 1
#define OPERATION_IDLE 0
#define OPERATION_FAILED 4

#define DISPLAY_QUEUE_LOW_LIMIT 3

