#!/bin/bash
# MSCC virtual audio cable — ALSA snd-aloop for PortAudio / mscc-init / digi apps
#
# Card "MSCCLoop":
#   PLAY  -> device 0  (digi app TX audio into cable)
#   CAPTURE <- device 1 (sdrcore-trans digital mic / MSCC_Cable_In)
#
# Friendly names in ~/.asoundrc:
#   MSCC_Cable_Out  MSCC_Cable_In
#
# Usage:  mscc-audio-setup | audio-setup  [start|stop|status|restart]
#
set -e

STATE="${HOME}/.mscc-virtual-audio.state"
ASOUND_SNIPPET="${HOME}/.asoundrc.mscc-virtual"
ASOUND_MAIN="${HOME}/.asoundrc"
CARD_ID="MSCCLoop"
# Prefer high index so we don't clash with HDMI/USB
CARD_INDEX="${MSCC_ALOOP_INDEX:-10}"

need_cmds() {
  for c in aplay arecord; do
    if ! command -v "$c" >/dev/null 2>&1; then
      echo "ERROR: $c not found. Install: sudo apt install -y alsa-utils" >&2
      exit 1
    fi
  done
}

# True if our card id or preferred index appears
card_present() {
  aplay -l 2>/dev/null | grep -q "\[${CARD_ID}\]" && return 0
  aplay -l 2>/dev/null | grep -q "^card ${CARD_INDEX}:" && return 0
  # stock name when module loaded without id=
  aplay -l 2>/dev/null | grep -qiE 'Loopback|loopback' && return 0
  return 1
}

find_card_num() {
  local n
  # Prefer explicit MSCCLoop id
  n=$(aplay -l 2>/dev/null | sed -n "s/^card \([0-9]*\): ${CARD_ID} .*/\1/p" | head -1)
  if [[ -z "$n" ]]; then
    n=$(aplay -l 2>/dev/null | sed -n "s/^card \([0-9]*\): .*\[${CARD_ID}\].*/\1/p" | head -1)
  fi
  if [[ -z "$n" ]]; then
    n=$(aplay -l 2>/dev/null | sed -n "s/^card \([0-9]*\): Loopback .*/\1/p" | head -1)
  fi
  if [[ -z "$n" ]]; then
    n=$(aplay -l 2>/dev/null | sed -n "s/^card \([0-9]*\): .*\[Loopback\].*/\1/p" | head -1)
  fi
  if [[ -z "$n" ]]; then
    n=$(aplay -l 2>/dev/null | sed -n "s/^card ${CARD_INDEX}:.*/${CARD_INDEX}/p" | head -1)
  fi
  echo "$n"
}

load_aloop() {
  # Prefer fixed index + id for stable naming across reboots
  if lsmod | grep -q '^snd_aloop'; then
    echo "  snd-aloop already loaded"
    return 0
  fi
  echo "  loading snd-aloop (may ask for sudo)..."
  if sudo modprobe snd-aloop enable=1,1 index="${CARD_INDEX}" id="${CARD_ID}"; then
    return 0
  fi
  echo "  retry plain: sudo modprobe snd-aloop enable=1,1"
  if sudo modprobe snd-aloop enable=1,1; then
    return 0
  fi
  echo "ERROR: could not load snd-aloop" >&2
  return 1
}

wait_for_card() {
  local i
  for i in 1 2 3 4 5 6 7 8 9 10; do
    if card_present; then
      return 0
    fi
    sleep 0.2
  done
  return 1
}

write_asoundrc() {
  local card="$1"
  # Use plughw so PortAudio rate/channel conversion is allowed (96 kHz duplex)
  cat >"$ASOUND_SNIPPET" <<EOF
# Auto-generated by mscc audio-setup — ALSA loopback for PortAudio
# Card ${card}: subdevice 0 = play (into cable), subdevice 1 = capture (from cable)

pcm.MSCC_Cable_Out {
    type plug
    slave {
        pcm "plughw:${card},0,0"
        rate 96000
        channels 2
    }
    hint {
        show on
        description "MSCC Virtual Cable Out"
    }
}
ctl.MSCC_Cable_Out {
    type hw
    card ${card}
}

pcm.MSCC_Cable_In {
    type plug
    slave {
        pcm "plughw:${card},1,0"
        rate 96000
        channels 2
    }
    hint {
        show on
        description "MSCC Virtual Cable In"
    }
}
ctl.MSCC_Cable_In {
    type hw
    card ${card}
}

pcm.mscc_out {
    type plug
    slave.pcm "MSCC_Cable_Out"
    hint { show on description "MSCC Virtual Cable Out" }
}
pcm.mscc_in {
    type plug
    slave.pcm "MSCC_Cable_In"
    hint { show on description "MSCC Virtual Cable In" }
}
EOF

  if [[ -f "$ASOUND_MAIN" ]]; then
    if ! grep -q 'asoundrc.mscc-virtual' "$ASOUND_MAIN" 2>/dev/null; then
      {
        echo ""
        echo "# MSCC virtual cable"
        echo "<${ASOUND_SNIPPET}>"
      } >>"$ASOUND_MAIN"
    fi
  else
    echo "<${ASOUND_SNIPPET}>" >"$ASOUND_MAIN"
  fi
  echo "  wrote $ASOUND_SNIPPET (card $card)"
}

remove_asoundrc() {
  rm -f "$ASOUND_SNIPPET"
  if [[ -f "$ASOUND_MAIN" ]]; then
    grep -v 'asoundrc.mscc-virtual' "$ASOUND_MAIN" 2>/dev/null | grep -v 'MSCC virtual cable' >"${ASOUND_MAIN}.tmp" || true
    if [[ ! -s "${ASOUND_MAIN}.tmp" ]]; then
      rm -f "$ASOUND_MAIN" "${ASOUND_MAIN}.tmp"
    else
      mv "${ASOUND_MAIN}.tmp" "$ASOUND_MAIN"
    fi
  fi
}

smoke_test_cable() {
  local card="$1"
  # Non-fatal: prove capture node opens (PortAudio needs this)
  if ! arecord -D "plughw:${card},1,0" -f S16_LE -r 48000 -c 2 -d 1 /dev/null 2>/tmp/mscc-aloop-arecord.err; then
    echo "WARNING: arecord on plughw:${card},1,0 failed — digital open may fail in sdrcore-trans"
    echo "---- arecord error ----"
    cat /tmp/mscc-aloop-arecord.err 2>/dev/null || true
    return 1
  fi
  echo "  smoke: capture plughw:${card},1,0 OK"
  return 0
}

do_stop() {
  echo "Stopping MSCC virtual cable names (module left loaded)..."
  remove_asoundrc
  rm -f "$STATE"
  echo "Removed ~/.asoundrc MSCC entries."
  echo "Unload module (optional):  sudo modprobe -r snd-aloop"
  echo "Stopped."
}

do_start() {
  need_cmds

  echo "Starting MSCC virtual cable (snd-aloop)..."
  load_aloop || exit 1

  if ! wait_for_card; then
    echo "ERROR: no loopback card in aplay -l after loading snd-aloop" >&2
    aplay -l || true
    exit 1
  fi

  local card
  card=$(find_card_num)
  if [[ -z "$card" ]]; then
    echo "ERROR: could not parse loopback card number" >&2
    aplay -l || true
    exit 1
  fi

  echo "  ALSA card number: $card"
  write_asoundrc "$card"
  echo "card=$card" >"$STATE"
  echo "id=$CARD_ID" >>"$STATE"
  echo "index=$CARD_INDEX" >>"$STATE"

  smoke_test_cable "$card" || true

  echo
  echo "Done. Use in mscc-init / PortAudio (digital mic = capture):"
  echo "  PLAY  (into cable):   MSCC_Cable_Out"
  echo "  RECORD (from cable):  MSCC_Cable_In"
  echo
  echo "Then: mscc-init  (pick MSCC_Cable_In for digital microphone)"
  echo "      mscc restart"
  echo
  do_status
}

do_status() {
  need_cmds
  echo "=== aplay -l ==="
  aplay -l 2>/dev/null || true
  echo
  echo "=== aplay -L | MSCC ==="
  aplay -L 2>/dev/null | grep -i MSCC || echo "(no MSCC play names — run: $0 start)"
  echo
  echo "=== arecord -L | MSCC ==="
  arecord -L 2>/dev/null | grep -i MSCC || echo "(no MSCC capture names)"
  echo
  if [[ -f "$STATE" ]]; then
    echo "State: $(tr '\n' ' ' <"$STATE")"
  else
    echo "State: not configured"
  fi
  lsmod | grep -q '^snd_aloop' && echo "snd_aloop: loaded" || echo "snd_aloop: not loaded"
  if [[ -f /etc/modprobe.d/mscc-aloop.conf ]]; then
    echo "modprobe.d: $(tr '\n' ' ' </etc/modprobe.d/mscc-aloop.conf)"
  fi
}

cmd="${1:-start}"
case "$cmd" in
  start)   do_start ;;
  stop)    do_stop ;;
  status)  do_status ;;
  restart) do_stop; sleep 0.3; do_start ;;
  -h|--help|help)
    echo "Usage: $0 [start|stop|status|restart]"
    ;;
  *)
    echo "Unknown: $cmd" >&2
    exit 1
    ;;
esac
