#pragma once

#define SEND_INTERVAL 100
#define SI570_DLL 0
#define SI5351_DLL 1
#define CALIBRATION_START 1
#define CALIBRATION_PROCESS 2
#define CALIBRATION_SUCCESS 3
#define CALIBRAITON_FAILED 0

#define CMD_SET_IQ_OFFSET 0x52
#define CMD_SET_SDR_CORE_BAND 0x53
#define IQ_CALIBRATION_TUNE 0x54
#define IQ_CALIBRATION_RX_TX 0x55
#define IQ_OPERATION_COMPLETE 0x56
#define CMD_SET_COMMIT_IQ 0x57
#define CMD_SET_IQ_BAND  0x58
#define IQ_IMAGE_CHECK_START 1
#define IQ_IMAGE_CHECK_STOP 2
#define IQ_IMAGE_CHECK_RUN 3

#define IQ_B2200 11
#define IQ_B630 10
#define IQ_B160  9
#define IQ_B80 8 
#define IQ_B60 7
#define IQ_B40 6
#define IQ_B30 5
#define IQ_B20 4
#define IQ_B17 3
#define IQ_B15 2
#define IQ_B12 1
#define IQ_B10 0
#define NO_IQ_BAND 200

#define CMD_SET_MONITOR 0x0D
#define CMD_SET_CALIBRATION_START 0x60
#define CMD_SET_CALIBRATION_DATA 0x61
#define CMD_SET_CALIBRATION_FINISHED 0x62
#define CMD_SET_CAL_LOOSE 0x63
#define CMD_CW_SNAP_DATA_PROCESSED 0x64
#define CMD_CW_SNAP_SET_DELTA 0x65
#define CMD_SET_CAL_DATA_PROCESSED 0x66
#define CMD_SET_CAL_FREQUENCY 0x67
#define CMD_SET_CAL_COURSE 0x68
#define CMD_SET_CAL_FINE 0x69
#define CMD_SET_CALIBRATIION_PROGRESS 0x6A
#define CMD_CW_SNAP_START 0x6C
#define CMD_CW_SNAP_FINISHED 0x6D
#define CMD_CW_SNAP_SET_CALIBRATION_DATA 0x6E
#define CDM_SET_CALIBRATE_CYCLE_COUNT 0x6F

#define SET_SIDE_TONE_VOLUME 0x7F

#define CMD_GET_SET_NB_ENABLE 0x80
#define CMD_GET_SET_NB_PULSE_WIDTH 0x81
#define CMD_GET_SET_NB_THRESHOLD 0x82
#define CMD_SET_IQ_DEFAULTS 0x8D
#define CMD_GET_IQ_VALUE 0x8B
#define CMD_GET_SET_AUTO_NOTCH 0x8E

#define CMD_GET_FREQ_INIT 0xB0
#define CMD_GET_FIRMWARE_VERSION 0xB2
#define CMD_GET_SET_MSSDR_VERSION 0xB3
#define CMD_GET_BAND_POWER 0xB4 
#define CMD_GET_SET_SDRCORE_RECV_VERSION 0xB5
#define CMD_SET_MAIN_FREQ 0xB6
#define CMD_SET_MAIN_MODE 0xB7
#define CMD_GET_MODE_INIT 0xB8
#define CMD_GET_BAND_INIT 0xB9
#define CMD_SET_TX_ON 0xBA
#define CMD_SET_DISPLAY_FREQ 0xBB
#define CMD_SET_TX_SET_BY_SERVER 0xBC
#define CMD_GET_SET_SDRCORE_TRANS_VERSION 0xBD
#define CMD_REPORT_IMAGE_VALUE 0xC6
#define CMD_START_STOP_IMAGE_VALUE 0xC7

//AF Filter Bandwidth
#define CMD_SET_BW_LOCUT 0xD0
#define CMD_SET_BW_HICUT 0xD1
#define CMD_SET_CW_PITCH 0xD2
#define CMD_SET_TX_HICUT 0xD3
#define CMD_GET_SET_SMETER 0xD4
#define CMD_GET_SET_PANADAPTER 0xD5
#define CMD_SET_CW_BW 0xDB
//Last Used
#define CMD_GET_LAST_USED_FREQ 0xD7
#define CMD_GET_LAST_USED_MODE 0xD8
#define CMD_GET_LAST_USED_BAND 0xD9


//Panadapter
#define CMD_GET_SET_PANADAPTER_SMOOTHING 0xDA
#define CMD_GET_SET_PANADAPTER_REFRESH 0x5F
#define CMD_GET_SET_PANADAPTER_GAIN 0x85
#define CMD_GET_SET_PANADAPTER_BASE 0x86
#define CMD_GET_SET_AGC 0x87
#define CMD_SET_AGC_FAST_LEVEL 0xCB

//Volume Management
#define CMD_SET_VOLUME_ATTN 0xE1
#define CMD_SET_AM_POWER 0xE3
#define CMD_SET_CW_POWER 0xE4
#define CMD_SET_SPEAKER_VOLUME 0xE5
#define CMD_SET_MIC_VOLUME 0xE6
#define CMD_SET_SPEAKER_MUTE 0xE7
#define CMD_SET_MIC_MUTE 0xE8

//Audio Device Selection
#define CMD_GET_SET_SPEAKER_DEVICE 0xEA
#define CMD_GET_SET_MIC_DEVICE 0xEB
#define CMD_DELETE_SDRCORE_INIT 0xEC


#define CMD_SET_HDSDR_STATUS 0xF0
#define CMD_GET_HDSDR_STATUS 0xF1
#define CMD_SET_POWER_MODE_STATE 0xF2
#define CMD_SET_PCB_VERSION 0xF3
#define CMD_SET_KEEP_ALIVE 0xF4
#define CMD_GUI_RUNNING 0xFE
#define CMD_SET_STOP 0xFF





